"""add_hps_tables

Revision ID: 0005
Revises: 0004
Create Date: 2024-12-21 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0005'
down_revision = '0004'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hps_requests',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('request_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('document_number', sa.String(length=50), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('first_last_name', sa.String(length=100), nullable=False),
    sa.Column('second_last_name', sa.String(length=100), nullable=True),
    sa.Column('nationality', sa.String(length=100), nullable=False),
    sa.Column('birth_place', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('submitted_by', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('approved_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hps_requests_id'), 'hps_requests', ['id'], unique=False)
    op.create_index(op.f('ix_hps_requests_request_type'), 'hps_requests', ['request_type'], unique=False)
    op.create_index(op.f('ix_hps_requests_status'), 'hps_requests', ['status'], unique=False)
    op.create_index(op.f('ix_hps_requests_user_id'), 'hps_requests', ['user_id'], unique=False)
    
    # Establecer estado por defecto para la columna status
    op.alter_column('hps_requests', 'status', server_default='pending')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hps_requests_user_id'), table_name='hps_requests')
    op.drop_index(op.f('ix_hps_requests_status'), table_name='hps_requests')
    op.drop_index(op.f('ix_hps_requests_request_type'), table_name='hps_requests')
    op.drop_index(op.f('ix_hps_requests_id'), table_name='hps_requests')
    op.drop_table('hps_requests')
    # ### end Alembic commands ###

