# Generated by Django 4.2.19 on 2025-02-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_albaran_movimientoproducto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoproducto',
            name='numero_serie',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo',
            field=models.CharField(blank=True, choices=[('C', 'C'), ('CC', 'CC')], max_length=2),
        ),
        migrations.AlterUniqueTogether(
            name='movimientoproducto',
            unique_together={('albaran', 'numero_serie')},
        ),
    ]
