# Generated by Django 4.2.19 on 2025-02-06 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_tipoproducto_alter_producto_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.tipoproducto'),
        ),
        migrations.CreateModel(
            name='PartNumberTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_producto', models.CharField(max_length=50, unique=True)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.tipoproducto')),
            ],
        ),
    ]
