# Generated by Django 4.2.19 on 2025-02-10 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('productos', '0005_alter_producto_tipo_partnumbertipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='albaran',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='albaranes_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='albaran',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='albaranes_actualizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movimientoproducto',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movimientoproducto',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_actualizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='producto',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='producto',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_actualizados', to=settings.AUTH_USER_MODEL),
        ),
    ]
