# Generated by Django 4.2.19 on 2025-02-25 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_lineatemporalproducto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PartNumberTipo',
        ),
    ]
