# Generated by Django 4.2.19 on 2025-02-28 09:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_delete_partnumbertipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='albaran',
            options={'ordering': ['-fecha']},
        ),
        migrations.AlterModelOptions(
            name='movimientoproducto',
            options={'ordering': ['-fecha']},
        ),
        migrations.RenameField(
            model_name='movimientoproducto',
            old_name='fecha_movimiento',
            new_name='fecha',
        ),
        migrations.AlterUniqueTogether(
            name='movimientoproducto',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='albaran',
            name='estado',
            field=models.CharField(choices=[('activo', 'En custodia'), ('inactivo', 'Fuera de custodia')], default='activo', max_length=20),
        ),
        migrations.AddField(
            model_name='movimientoproducto',
            name='estado_anterior',
            field=models.CharField(choices=[('activo', 'En custodia'), ('inactivo', 'Fuera de custodia')], default='inactivo', max_length=20),
        ),
        migrations.AddField(
            model_name='movimientoproducto',
            name='estado_nuevo',
            field=models.CharField(choices=[('activo', 'En custodia'), ('inactivo', 'Fuera de custodia')], default='activo', max_length=20),
        ),
        migrations.AddField(
            model_name='movimientoproducto',
            name='tipo_movimiento',
            field=models.CharField(choices=[('inventario', 'Entrada por inventario'), ('transferencia', 'Transferencia (AC21)'), ('entrega_mano', 'Entrega en mano (AC21)')], default='inventario', max_length=50),
        ),
        migrations.AddField(
            model_name='producto',
            name='albaran',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='productos.albaran'),
        ),
        migrations.AddField(
            model_name='producto',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='producto',
            name='estado_actual',
            field=models.CharField(choices=[('activo', 'En custodia'), ('inactivo', 'Fuera de custodia')], default='activo', max_length=20),
        ),
        migrations.AddField(
            model_name='producto',
            name='ultima_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='albaran',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='albaran',
            name='numero',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='albaran',
            name='tipo_entrada',
            field=models.CharField(choices=[('inventario', 'Entrada por inventario'), ('transferencia', 'Transferencia (AC21)'), ('entrega_mano', 'Entrega en mano (AC21)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='movimientoproducto',
            name='albaran',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.albaran'),
        ),
        migrations.AlterField(
            model_name='movimientoproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='productos.producto'),
        ),
        migrations.AlterUniqueTogether(
            name='albaran',
            unique_together={('numero', 'fecha', 'tipo_entrada')},
        ),
        migrations.RemoveField(
            model_name='albaran',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='albaran',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='movimientoproducto',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='movimientoproducto',
            name='numero_serie',
        ),
        migrations.RemoveField(
            model_name='movimientoproducto',
            name='updated_by',
        ),
    ]
