# Generated by Django 4.2.19 on 2025-02-28 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0009_alter_albaran_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='estado_actual',
        ),
        migrations.CreateModel(
            name='InventarioProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('activo', 'En custodia'), ('inactivo', 'Fuera de custodia')], default='activo', max_length=20)),
                ('ubicacion', models.CharField(blank=True, max_length=100, null=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='productos.producto')),
            ],
            options={
                'verbose_name': 'Inventario de Producto',
                'verbose_name_plural': 'Inventario de Productos',
            },
        ),
    ]
