# Generated by Django 4.2.19 on 2025-02-28 10:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('productos', '0010_remove_producto_estado_actual_inventarioproducto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Producto',
            new_name='CatalogoProducto',
        ),
        migrations.AlterModelOptions(
            name='catalogoproducto',
            options={'verbose_name': 'Catálogo de Producto', 'verbose_name_plural': 'Catálogo de Productos'},
        ),
    ]
