# Generated by Django 4.2.19 on 2025-02-28 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0011_rename_producto_catalogoproducto_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogoproducto',
            options={'ordering': ['codigo_producto'], 'verbose_name': 'Catálogo de Producto', 'verbose_name_plural': 'Catálogo de Productos'},
        ),
        migrations.AddField(
            model_name='inventarioproducto',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inventarioproducto',
            name='ultimo_movimiento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventario_actual', to='productos.movimientoproducto'),
        ),
        migrations.AddField(
            model_name='movimientoproducto',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inventarioproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='productos.catalogoproducto'),
        ),
        migrations.AlterUniqueTogether(
            name='inventarioproducto',
            unique_together={('producto', 'numero_serie')},
        ),
        migrations.AlterUniqueTogether(
            name='movimientoproducto',
            unique_together={('producto', 'numero_serie', 'albaran')},
        ),
    ]
