# Generated by Django 4.2.19 on 2025-03-04 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('productos', '0012_alter_catalogoproducto_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=200)),
                ('ciudad', models.CharField(max_length=100)),
                ('codigo_postal', models.CharField(max_length=10)),
                ('provincia', models.CharField(max_length=100)),
                ('codigo_odmc', models.CharField(blank=True, max_length=20)),
                ('codigo_emad', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='albaran',
            options={'ordering': ['-fecha'], 'verbose_name': 'Albarán', 'verbose_name_plural': 'Albaranes'},
        ),
        migrations.AlterUniqueTogether(
            name='albaran',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='albaran',
            name='codigo_contabilidad',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='albaran',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='albaran',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='albaranes_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='albaran',
            name='destinatario_autorizado_cargo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='albaran',
            name='destinatario_autorizado_nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='albaran',
            name='estado_material',
            field=models.CharField(choices=[('RECIBIDO', 'Recibido'), ('INVENTARIADO', 'Inventariado'), ('DESTRUIDO', 'Destruido')], default='RECIBIDO', max_length=20),
        ),
        migrations.AddField(
            model_name='albaran',
            name='fecha_informe',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='albaran',
            name='fecha_transaccion',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='albaran',
            name='firma_remitente_cargo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='albaran',
            name='firma_remitente_nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='albaran',
            name='numero_registro_entrada',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='albaran',
            name='numero_registro_salida',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='albaran',
            name='observaciones_odmc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='albaran',
            name='odmc_numero',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='albaran',
            name='requiere_testigo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='albaran',
            name='tipo_documento',
            field=models.CharField(blank=True, choices=[('TRANSFERENCIA', 'Transferencia'), ('INVENTARIO', 'Inventario'), ('DESTRUCCION', 'Destrucción'), ('RECIBO_MANO', 'Recibo en Mano'), ('OTRO', 'Otro')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='albaran',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='albaran',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='albaranes_actualizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='albaran',
            name='numero',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='albaran',
            name='tipo_entrada',
            field=models.CharField(max_length=20),
        ),
        migrations.RemoveField(
            model_name='albaran',
            name='estado',
        ),
        migrations.AddField(
            model_name='albaran',
            name='empresa_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='albaranes_como_destino', to='productos.empresa', verbose_name='PARA'),
        ),
        migrations.AddField(
            model_name='albaran',
            name='empresa_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='albaranes_como_origen', to='productos.empresa', verbose_name='DE'),
        ),
    ]
