# Generated by Django 4.2.19 on 2025-03-04 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0013_empresa_alter_albaran_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='activa',
            field=models.BooleanField(default=True),
        ),
    ]
