# Generated by Django 4.2.21 on 2025-05-26 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0014_empresa_activa'),
    ]

    operations = [
        migrations.AddField(
            model_name='albaran',
            name='firma_a_cargo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='albaran',
            name='firma_a_empleo_rango',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='albaran',
            name='firma_a_nombre_apellidos',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='albaran',
            name='firma_b_cargo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='albaran',
            name='firma_b_empleo_rango',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='albaran',
            name='firma_b_nombre_apellidos',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
