# Generated by Django 4.2.21 on 2025-05-26 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0015_add_firma_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='albaran',
            name='firma_a',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Firma A'),
        ),
        migrations.AddField(
            model_name='albaran',
            name='firma_b',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Firma B'),
        ),
        migrations.AlterField(
            model_name='albaran',
            name='firma_a_cargo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo A'),
        ),
        migrations.AlterField(
            model_name='albaran',
            name='firma_a_empleo_rango',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Empleo/Rango A'),
        ),
        migrations.AlterField(
            model_name='albaran',
            name='firma_a_nombre_apellidos',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre y Apellidos A'),
        ),
        migrations.AlterField(
            model_name='albaran',
            name='firma_b_cargo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo B'),
        ),
        migrations.AlterField(
            model_name='albaran',
            name='firma_b_empleo_rango',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Empleo/Rango B'),
        ),
        migrations.AlterField(
            model_name='albaran',
            name='firma_b_nombre_apellidos',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre y Apellidos B'),
        ),
    ]
