# Generated by Django 4.2.21 on 2025-05-27 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0016_add_firma_fields_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventarioproducto',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimientoproducto',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
