# Generated by Django 4.2.21 on 2025-06-05 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0017_inventarioproducto_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='albaran',
            name='direccion_transferencia',
            field=models.CharField(blank=True, choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida')], help_text='Para AC21s (transferencias), indica si es una entrada o una salida.', max_length=10, null=True),
        ),
    ]
