# Generated by Django 4.2.21 on 2025-06-05 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0018_albaran_direccion_transferencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albaran',
            name='tipo_entrada',
            field=models.CharField(choices=[('inventario', 'Entrada por inventario'), ('transferencia', 'Transferencia (AC21)'), ('entrega_mano', 'Entrega en mano (AC21)')], default='inventario', max_length=20),
        ),
    ]
