# Generated by Django 4.2.21 on 2025-06-05 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0019_alter_albaran_tipo_entrada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albaran',
            name='tipo_entrada',
        ),
        migrations.AlterField(
            model_name='albaran',
            name='tipo_documento',
            field=models.CharField(blank=True, choices=[('TRANSFERENCIA', 'Transferencia'), ('INVENTARIO', 'Inventario'), ('DESTRUCCION', 'Destrucción'), ('RECIBO_MANO', 'Recibo en Mano'), ('OTRO', 'Otro')], max_length=20, null=True, verbose_name='Tipo de Operación'),
        ),
        migrations.AlterField(
            model_name='movimientoproducto',
            name='tipo_movimiento',
            field=models.CharField(choices=[('TRANSFERENCIA', 'Transferencia'), ('INVENTARIO', 'Inventario'), ('DESTRUCCION', 'Destrucción'), ('RECIBO_MANO', 'Recibo en Mano'), ('OTRO', 'Otro')], default='INVENTARIO', max_length=20),
        ),
    ]
