# Generated by Django 4.2.21 on 2025-06-05 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0020_remove_albaran_tipo_entrada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albaran',
            name='tipo_documento',
            field=models.CharField(blank=True, choices=[('TRANSFERENCIA', 'Transferencia'), ('INVENTARIO', 'Inventario'), ('DESTRUCCION', 'Destrucción'), ('RECIBO_MANO', 'Recibo en Mano'), ('OTRO', 'Otro')], max_length=20, null=True, verbose_name='Tipo de transacción'),
        ),
    ]
