# Generated by Django 4.2.23 on 2025-06-19 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0022_add_accesorios_equipos_prueba'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albaran',
            name='tipo_documento',
            field=models.CharField(blank=True, choices=[('TRANSFERENCIA', 'Transferencia'), ('INVENTARIO', 'Inventario'), ('DESTRUCCION', 'Destrucción'), ('RECIBO_MANO', 'Recibo en Mano'), ('OTRO', 'Otro')], max_length=20, null=True, verbose_name='Tipo de Operación'),
        ),
    ]
