# Generated by Django 4.2.23 on 2025-06-23 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0023_alter_albaran_tipo_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineatemporalproducto',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='lineatemporalproducto',
            name='cc',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='lineatemporalproducto',
            name='datos_adicionales',
            field=models.JSONField(blank=True, default=dict, help_text='Información adicional del AC21 (cabecera, empresas, firmas, etc.)', null=True),
        ),
    ]
