# Generated by Django 4.2.23 on 2025-06-23 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0024_lineatemporalproducto_cantidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoproducto',
            name='cantidad',
            field=models.IntegerField(default=1, help_text='Cantidad del producto en el movimiento'),
        ),
        migrations.AddField(
            model_name='movimientoproducto',
            name='cc',
            field=models.IntegerField(default=1, help_text='Campo CC del AC-21'),
        ),
        migrations.AddField(
            model_name='movimientoproducto',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Observaciones específicas del movimiento', null=True),
        ),
    ]
