# Generated by Django 4.2.23 on 2025-06-23 21:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0025_movimientoproducto_cantidad_movimientoproducto_cc_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lineatemporalproducto',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='lineatemporalproducto',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lineatemporalproducto',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
