# Generated by Django 4.2.23 on 2025-06-24 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0026_alter_lineatemporalproducto_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albaran',
            name='estado_material',
            field=models.CharField(blank=True, choices=[('RECIBIDO', 'Recibido'), ('INVENTARIADO', 'Inventariado'), ('DESTRUIDO', 'Destruido')], help_text='Estado del material: RECIBIDO, INVENTARIADO o DESTRUIDO', max_length=20, null=True),
        ),
    ]
