# Generated by Django 4.2.23 on 2025-06-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0027_alter_albaran_estado_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albaran',
            name='requiere_testigo',
        ),
        migrations.AddField(
            model_name='albaran',
            name='destinatario_autorizado_otro',
            field=models.BooleanField(default=False, verbose_name='Destinatario autorizado - OTRO'),
        ),
        migrations.AddField(
            model_name='albaran',
            name='destinatario_autorizado_otro_especificar',
            field=models.CharField(blank=True, help_text='Especificar el tipo cuando se selecciona OTRO', max_length=200, null=True, verbose_name='Destinatario autorizado - Especificar OTRO'),
        ),
        migrations.AddField(
            model_name='albaran',
            name='destinatario_autorizado_testigo',
            field=models.BooleanField(default=False, verbose_name='Destinatario autorizado - TESTIGO'),
        ),
    ]
