# Generated by Django 4.2.23 on 2025-06-24 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0028_remove_albaran_requiere_testigo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='albaran',
            name='documento_principal',
            field=models.ForeignKey(blank=True, help_text='Referencia al documento principal si esta es una página adicional', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paginas_adicionales', to='productos.albaran'),
        ),
        migrations.AddField(
            model_name='albaran',
            name='pagina_numero',
            field=models.IntegerField(default=1, help_text='Número de página del documento'),
        ),
        migrations.AddField(
            model_name='albaran',
            name='total_paginas',
            field=models.IntegerField(default=1, help_text='Total de páginas del documento'),
        ),
    ]
