# Generated by Django 4.2.23 on 2025-06-25 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0029_albaran_documento_principal_albaran_pagina_numero_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='codigo_emad',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='codigo_odmc',
        ),
        migrations.AddField(
            model_name='empresa',
            name='numero_odmc',
            field=models.CharField(blank=True, max_length=20, verbose_name='Número ODMC'),
        ),
    ]
