# Generated by Django 4.2.23 on 2025-06-26 11:09

from django.db import migrations, models
import productos.models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0031_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='albaran',
            name='imagen_documento',
            field=models.ImageField(blank=True, help_text='Imagen del documento AC21 procesado (rotada y optimizada)', null=True, upload_to=productos.models.imagen_documento_upload_path),
        ),
    ]
