# Generated by Django 4.2.27 on 2026-01-26 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0033_remove_catalogoproducto_tipo_cryptocustodio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineatemporalproducto',
            name='cc',
        ),
        migrations.AddField(
            model_name='lineatemporalproducto',
            name='tipo_producto',
            field=models.ForeignKey(blank=True, help_text='Tipo de cryptocustodio para tipificación de la línea temporal', null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.tipoproducto'),
        ),
        migrations.AlterField(
            model_name='lineatemporalproducto',
            name='datos_adicionales',
            field=models.JSONField(blank=True, default=dict, help_text='Información adicional del AC21 (cabecera, empresas, firmas, cc del OCR, etc.)', null=True),
        ),
    ]
