"""add_government_hps_fields

Revision ID: 3289eb4eac14
Revises: b8cc47cb27f2
Create Date: 2025-10-10 11:13:31.822113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3289eb4eac14'
down_revision = 'b8cc47cb27f2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hps_requests', sa.Column('security_clearance_level', sa.String(length=255), nullable=True))
    op.add_column('hps_requests', sa.Column('government_expediente', sa.String(length=50), nullable=True))
    op.add_column('hps_requests', sa.Column('company_name', sa.String(length=255), nullable=True))
    op.add_column('hps_requests', sa.Column('company_nif', sa.String(length=20), nullable=True))
    op.add_column('hps_requests', sa.Column('internal_code', sa.String(length=50), nullable=True))
    op.add_column('hps_requests', sa.Column('job_position', sa.String(length=100), nullable=True))
    op.add_column('hps_requests', sa.Column('auto_processed', sa.Boolean(), nullable=True))
    op.add_column('hps_requests', sa.Column('source_pdf_filename', sa.String(length=255), nullable=True))
    op.add_column('hps_requests', sa.Column('auto_processed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('hps_requests', sa.Column('government_document_type', sa.String(length=100), nullable=True))
    op.add_column('hps_requests', sa.Column('data_source', sa.String(length=50), nullable=True))
    op.add_column('hps_requests', sa.Column('original_status_text', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_hps_requests_company_nif'), 'hps_requests', ['company_nif'], unique=False)
    op.create_index(op.f('ix_hps_requests_government_expediente'), 'hps_requests', ['government_expediente'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hps_requests_government_expediente'), table_name='hps_requests')
    op.drop_index(op.f('ix_hps_requests_company_nif'), table_name='hps_requests')
    op.drop_column('hps_requests', 'original_status_text')
    op.drop_column('hps_requests', 'data_source')
    op.drop_column('hps_requests', 'government_document_type')
    op.drop_column('hps_requests', 'auto_processed_at')
    op.drop_column('hps_requests', 'source_pdf_filename')
    op.drop_column('hps_requests', 'auto_processed')
    op.drop_column('hps_requests', 'job_position')
    op.drop_column('hps_requests', 'internal_code')
    op.drop_column('hps_requests', 'company_nif')
    op.drop_column('hps_requests', 'company_name')
    op.drop_column('hps_requests', 'government_expediente')
    op.drop_column('hps_requests', 'security_clearance_level')
    # ### end Alembic commands ###
