"""add_closed_at_to_chat_conversations

Revision ID: b8cc47cb27f2
Revises: 
Create Date: 2025-10-09 09:24:27.591335

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b8cc47cb27f2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_satisfaction')
    op.add_column('chat_conversations', sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('chat_conversations', 'satisfaction_feedback')
    op.drop_column('chat_conversations', 'user_satisfaction')
    op.create_index(op.f('ix_hps_requests_type'), 'hps_requests', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hps_requests_type'), table_name='hps_requests')
    op.add_column('chat_conversations', sa.Column('user_satisfaction', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('chat_conversations', sa.Column('satisfaction_feedback', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('chat_conversations', 'closed_at')
    op.create_table('user_satisfaction',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('conversation_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('feedback', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('is_anonymous', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['chat_conversations.id'], name='user_satisfaction_conversation_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_satisfaction_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_satisfaction_pkey')
    )
    # ### end Alembic commands ###
