# Generated by Django 5.2.8 on 2025-11-21 11:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HpsRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('permissions', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rol HPS',
                'verbose_name_plural': 'Roles HPS',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HpsTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('template_pdf', models.FileField(upload_to='hps/templates/')),
                ('template_type', models.CharField(choices=[('jefe_seguridad', 'Jefe de seguridad'), ('jefe_seguridad_suplente', 'Jefe suplente')], default='jefe_seguridad', max_length=50)),
                ('version', models.CharField(default='1.0', max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plantilla HPS',
                'verbose_name_plural': 'Plantillas HPS',
                'ordering': ['name', 'version'],
            },
        ),
        migrations.CreateModel(
            name='HpsAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=100)),
                ('table_name', models.CharField(blank=True, max_length=100)),
                ('record_id', models.UUIDField(blank=True, null=True)),
                ('old_values', models.JSONField(blank=True, null=True)),
                ('new_values', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hps_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de auditoría HPS',
                'verbose_name_plural': 'Logs de auditoría HPS',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HpsTeam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hps_led_teams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Equipo HPS',
                'verbose_name_plural': 'Equipos HPS',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HpsUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_verified', models.BooleanField(default=False)),
                ('is_temp_password', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('extra_permissions', models.JSONField(blank=True, default=dict)),
                ('must_change_password', models.BooleanField(default=False)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profiles', to='hps_core.hpsrole')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='hps_core.hpsteam')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hps_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de usuario HPS',
                'verbose_name_plural': 'Perfiles de usuario HPS',
            },
        ),
        migrations.CreateModel(
            name='HpsTeamMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_lead', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='hps_core.hpsteam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hps_team_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membresía de equipo HPS',
                'verbose_name_plural': 'Membresías de equipo HPS',
                'unique_together': {('team', 'user')},
            },
        ),
        migrations.CreateModel(
            name='HpsRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_type', models.CharField(choices=[('new', 'Alta'), ('renewal', 'Renovación'), ('transfer', 'Traslado')], default='new', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobada'), ('rejected', 'Rechazada'), ('expired', 'Expirada')], default='pending', max_length=50)),
                ('form_type', models.CharField(choices=[('solicitud', 'Solicitud'), ('traslado', 'Traslado')], default='solicitud', max_length=20)),
                ('filled_pdf', models.FileField(blank=True, null=True, upload_to='hps/filled/')),
                ('response_pdf', models.FileField(blank=True, null=True, upload_to='hps/responses/')),
                ('document_type', models.CharField(max_length=50)),
                ('document_number', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
                ('first_name', models.CharField(max_length=100)),
                ('first_last_name', models.CharField(max_length=100)),
                ('second_last_name', models.CharField(blank=True, max_length=100)),
                ('nationality', models.CharField(max_length=100)),
                ('birth_place', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('security_clearance_level', models.CharField(blank=True, max_length=255)),
                ('government_expediente', models.CharField(blank=True, max_length=50)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('company_nif', models.CharField(blank=True, max_length=20)),
                ('internal_code', models.CharField(blank=True, max_length=50)),
                ('job_position', models.CharField(blank=True, max_length=100)),
                ('auto_processed', models.BooleanField(default=False)),
                ('source_pdf_filename', models.CharField(blank=True, max_length=255)),
                ('auto_processed_at', models.DateTimeField(blank=True, null=True)),
                ('government_document_type', models.CharField(blank=True, max_length=100)),
                ('data_source', models.CharField(blank=True, default='manual', max_length=50)),
                ('original_status_text', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_hps_requests', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_hps_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hps_requests', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hps_core.hpstemplate')),
            ],
            options={
                'verbose_name': 'Solicitud HPS',
                'verbose_name_plural': 'Solicitudes HPS',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='hps_core_hp_status_48e63e_idx'), models.Index(fields=['request_type'], name='hps_core_hp_request_8634d5_idx'), models.Index(fields=['government_expediente'], name='hps_core_hp_governm_1e5387_idx')],
            },
        ),
        migrations.CreateModel(
            name='HpsToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('purpose', models.CharField(blank=True, max_length=500)),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_hps_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token HPS',
                'verbose_name_plural': 'Tokens HPS',
                'indexes': [models.Index(fields=['token'], name='hps_core_hp_token_64ed24_idx'), models.Index(fields=['expires_at'], name='hps_core_hp_expires_c4781d_idx')],
            },
        ),
    ]
