# Generated by Django 5.2.8 on 2025-11-25 07:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hps_core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(db_index=True, max_length=255)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('active', 'Activa'), ('closed', 'Cerrada'), ('archived', 'Archivada')], default='active', max_length=50)),
                ('total_messages', models.IntegerField(default=0)),
                ('total_tokens_used', models.IntegerField(default=0)),
                ('conversation_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversación de Chat',
                'verbose_name_plural': 'Conversaciones de Chat',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_type', models.CharField(choices=[('user', 'Usuario'), ('assistant', 'Asistente'), ('system', 'Sistema')], max_length=50)),
                ('content', models.TextField()),
                ('tokens_used', models.IntegerField(default=0)),
                ('response_time_ms', models.IntegerField(blank=True, null=True)),
                ('is_error', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('message_metadata', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='hps_core.chatconversation')),
            ],
            options={
                'verbose_name': 'Mensaje de Chat',
                'verbose_name_plural': 'Mensajes de Chat',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(db_index=True)),
                ('total_conversations', models.IntegerField(default=0)),
                ('total_messages', models.IntegerField(default=0)),
                ('total_tokens_used', models.IntegerField(default=0)),
                ('avg_response_time_ms', models.FloatField(default=0.0)),
                ('avg_satisfaction_rating', models.FloatField(default=0.0)),
                ('error_rate', models.FloatField(default=0.0)),
                ('active_users', models.IntegerField(default=0)),
                ('peak_concurrent_users', models.IntegerField(default=0)),
                ('most_common_topics', models.TextField(blank=True)),
                ('system_health_score', models.FloatField(default=100.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Métrica de Chat',
                'verbose_name_plural': 'Métricas de Chat',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='hps_core_ch_date_e6a648_idx')],
            },
        ),
        migrations.CreateModel(
            name='HpsUserMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hps_user_uuid', models.UUIDField(db_index=True, unique=True)),
                ('migrated_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('django_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hps_mapping', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mapeo de Usuario HPS',
                'verbose_name_plural': 'Mapeos de Usuarios HPS',
                'ordering': ['-migrated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='chatconversation',
            index=models.Index(fields=['user', '-created_at'], name='hps_core_ch_user_id_7bc1cb_idx'),
        ),
        migrations.AddIndex(
            model_name='chatconversation',
            index=models.Index(fields=['session_id'], name='hps_core_ch_session_6c74cf_idx'),
        ),
        migrations.AddIndex(
            model_name='chatconversation',
            index=models.Index(fields=['status'], name='hps_core_ch_status_23a1db_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['conversation', 'created_at'], name='hps_core_ch_convers_90b069_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['message_type'], name='hps_core_ch_message_1fffba_idx'),
        ),
    ]
