# Generated by Django 4.2.26 on 2025-11-25 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hps_core', '0002_chatconversation_chatmessage_chatmetrics_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hpsrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('submitted', 'Enviada'), ('approved', 'Aprobada'), ('rejected', 'Rechazada'), ('expired', 'Expirada')], default='pending', max_length=50),
        ),
    ]
