# Generated by Django 4.2.27 on 2025-12-05 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hps_core', '0003_alter_hpsrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hpsrequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_hps_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hpsrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('waiting_dps', 'Esperando DPS'), ('submitted', 'Enviada'), ('approved', 'Aprobada'), ('rejected', 'Rechazada'), ('expired', 'Expirada')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='hpsrequest',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_hps_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hpsrequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hps_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
