"""
Django settings for cryptotrace_backend project.

Generated by 'django-admin startproject' using Django 4.2.18.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url
from datetime import timedelta

# 🔥 Cargar variables del archivo .env automáticamente
from dotenv import load_dotenv
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY debe venir de variable de entorno
# settings_dev.py y settings_prod.py manejarán los fallbacks/validación según corresponda
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG debe venir de variable de entorno
# settings_dev.py y settings_prod.py lo configurarán según corresponda
DEBUG = os.getenv('DEBUG', 'False').lower() == 'true'

# ALLOWED_HOSTS debe venir de variable de entorno
# settings_dev.py y settings_prod.py manejarán los fallbacks/validación según corresponda
ALLOWED_HOSTS_STR = os.getenv('ALLOWED_HOSTS', '')
ALLOWED_HOSTS = [host.strip() for host in ALLOWED_HOSTS_STR.split(',') if host.strip()] if ALLOWED_HOSTS_STR else []



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',  # Django REST Framework
    'rest_framework_simplejwt',
    'productos',       # Nuestra nueva aplicación
    'django_extensions',  # Agregar esta línea
    "corsheaders",
    "hps_core",
    'channels',  # Django Channels para WebSocket
    'hps_agent',  # Agente IA integrado en Django

]


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

# Configuración JWT unificada (compatible con hps-system)
# hps-system usa 480 minutos (8 horas), cryptotrace usa 1 hora
# Usamos configuración desde variables de entorno con fallback
ACCESS_TOKEN_EXPIRE_MINUTES = int(os.getenv('ACCESS_TOKEN_EXPIRE_MINUTES', '480'))  # 8 horas por defecto (hps-system)

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=ACCESS_TOKEN_EXPIRE_MINUTES),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),  # Refresh token válido por 7 días
    'AUTH_HEADER_TYPES': ('Bearer',),
    'ALGORITHM': os.getenv('JWT_ALGORITHM', 'HS256'),
    'SIGNING_KEY': os.getenv('JWT_SECRET_KEY', SECRET_KEY),  # Usar JWT_SECRET_KEY si está disponible
}


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# CORS_ALLOWED_ORIGINS debe venir de variable de entorno
# settings_dev.py y settings_prod.py manejarán los fallbacks/validación según corresponda
CORS_ORIGINS_STR = os.getenv('CORS_ALLOWED_ORIGINS', '')
CORS_ALLOWED_ORIGINS = [origin.strip() for origin in CORS_ORIGINS_STR.split(',') if origin.strip()] if CORS_ORIGINS_STR else []

# CORS_ALLOW_ALL_ORIGINS debe venir de variable de entorno
CORS_ALLOW_ALL_ORIGINS = os.getenv('CORS_ALLOW_ALL_ORIGINS', 'False').lower() == 'true'
CORS_ALLOW_CREDENTIALS = True


ROOT_URLCONF = 'cryptotrace_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'productos', 'templates'),  # 🔥 Agregar templates de emails
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'cryptotrace_backend.wsgi.application'
ASGI_APPLICATION = 'cryptotrace_backend.asgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=os.getenv('DATABASE_URL', 'postgres://cryptotrace_user:cryptotrace_pass@db:5432/cryptotrace_db')
    )
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ===== CONFIGURACIÓN DE ARCHIVOS MEDIA =====
# Directorio donde se guardan los archivos subidos por los usuarios
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# URL base para servir archivos media
MEDIA_URL = '/media/'

# Asegurarse de que el directorio media existe
if not os.path.exists(MEDIA_ROOT):
    os.makedirs(MEDIA_ROOT, exist_ok=True)

# Crear subdirectorios necesarios para HPS
HPS_TEMPLATES_DIR = os.path.join(MEDIA_ROOT, 'hps', 'templates')
HPS_FILLED_DIR = os.path.join(MEDIA_ROOT, 'hps', 'filled')
HPS_RESPONSES_DIR = os.path.join(MEDIA_ROOT, 'hps', 'responses')

for directory in [HPS_TEMPLATES_DIR, HPS_FILLED_DIR, HPS_RESPONSES_DIR]:
    if not os.path.exists(directory):
        os.makedirs(directory, exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'django.log'),
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}

# Asegurarse de que el directorio de logs existe
LOGS_DIR = os.path.join(BASE_DIR, 'logs')
if not os.path.exists(LOGS_DIR):
    os.makedirs(LOGS_DIR, exist_ok=True)

# ===== CONFIGURACIÓN DE EMAIL =====
# Configuración unificada desde hps-system y cryptotrace
# Cambiar temporalmente a console para testing
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  # 🔥 TEMPORAL: mostrar en consola
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# SMTP Configuration (compatible con hps-system)
# Acepta tanto SMTP_* como EMAIL_* para compatibilidad con ambos sistemas
EMAIL_HOST = os.getenv('SMTP_HOST', os.getenv('EMAIL_HOST', 'smtp.gmail.com'))
EMAIL_PORT = int(os.getenv('SMTP_PORT', os.getenv('EMAIL_PORT', '587')))
EMAIL_USE_TLS = os.getenv('SMTP_USE_TLS', os.getenv('EMAIL_USE_TLS', 'True')).lower() == 'true'
EMAIL_USE_SSL = os.getenv('EMAIL_USE_SSL', 'False').lower() == 'true'
EMAIL_HOST_USER = os.getenv('SMTP_USER', os.getenv('EMAIL_HOST_USER', ''))
EMAIL_HOST_PASSWORD = os.getenv('SMTP_PASSWORD', os.getenv('EMAIL_HOST_PASSWORD', ''))
EMAIL_TIMEOUT = 30  # Timeout en segundos

# Configuración de nombres y reply-to (desde hps-system)
SMTP_FROM_NAME = os.getenv('SMTP_FROM_NAME', 'CryptoTrace HPS')
SMTP_FROM_EMAIL = os.getenv('SMTP_FROM_EMAIL', '')  # Email específico para "From" (opcional)
SMTP_REPLY_TO = os.getenv('SMTP_REPLY_TO', os.getenv('EMAIL_HOST_USER', ''))
# Si SMTP_FROM_EMAIL está definido, usarlo; sino construir con SMTP_FROM_NAME + SMTP_USER
if SMTP_FROM_EMAIL:
    DEFAULT_FROM_EMAIL = SMTP_FROM_EMAIL
elif EMAIL_HOST_USER:
    DEFAULT_FROM_EMAIL = f"{SMTP_FROM_NAME} <{EMAIL_HOST_USER}>"
else:
    DEFAULT_FROM_EMAIL = "CryptoTrace (AICOX) <noreply@cryptotrace.local>"

# Configuraciones específicas para PrivateEmail
EMAIL_USE_LOCALTIME = False
SERVER_EMAIL = DEFAULT_FROM_EMAIL

# IMAP Configuration (para procesar correos entrantes del gobierno)
IMAP_HOST = os.getenv('IMAP_HOST', 'imap.gmail.com')
IMAP_PORT = int(os.getenv('IMAP_PORT', '993'))
IMAP_USER = os.getenv('IMAP_USER', EMAIL_HOST_USER)
IMAP_PASSWORD = os.getenv('IMAP_PASSWORD', EMAIL_HOST_PASSWORD)
IMAP_MAILBOX = os.getenv('IMAP_MAILBOX', 'INBOX')

# URL base del frontend para incluir en emails
# settings_dev.py y settings_prod.py manejarán los fallbacks/validación según corresponda
FRONTEND_URL = os.getenv('FRONTEND_URL')
# URL del sistema HPS (para emails de credenciales HPS)
# settings_dev.py y settings_prod.py manejarán los fallbacks/validación según corresponda
HPS_SYSTEM_URL = os.getenv('HPS_SYSTEM_URL')
# URL del sistema HPS para Next.js (CryptoTrace frontend)
NEXT_PUBLIC_HPS_SYSTEM_URL = os.getenv('NEXT_PUBLIC_HPS_SYSTEM_URL')

# === Celery / Redis (configuración unificada desde hps-system) ===
# Redis Configuration
# settings_dev.py y settings_prod.py manejarán los fallbacks/validación según corresponda
REDIS_HOST = os.getenv("REDIS_HOST")
REDIS_PORT = int(os.getenv("REDIS_PORT", "6379")) if os.getenv("REDIS_PORT") else 6379
REDIS_URL = os.getenv("REDIS_URL")
if not REDIS_URL and REDIS_HOST:
    REDIS_URL = f"redis://{REDIS_HOST}:{REDIS_PORT}/0"

# Celery Configuration (compatible con hps-system)
CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", REDIS_URL)
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", REDIS_URL)

# === Django Channels Configuration ===
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [(REDIS_HOST, REDIS_PORT)],
        },
    },
}

CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = os.getenv("CELERY_TIMEZONE", "UTC")
CELERY_ENABLE_UTC = True
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutos
CELERY_TASK_SOFT_TIME_LIMIT = 25 * 60  # 25 minutos
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_WORKER_MAX_TASKS_PER_CHILD = 1000
CELERY_RESULT_EXPIRES = 3600  # 1 hora

# Colas separadas (desde hps-system)
CELERY_TASK_ROUTES = {
    # Tareas de email HPS específicas
    "hps_core.tasks.send_hps_credentials_email": {"queue": "email"},
    "hps_core.tasks.send_hps_confirmation_email": {"queue": "email"},
    "hps_core.tasks.send_hps_status_update_email": {"queue": "email"},
    "hps_core.tasks.send_hps_approved_email": {"queue": "email"},
    "hps_core.tasks.send_hps_rejected_email": {"queue": "email"},
    "hps_core.tasks.send_hps_form_email_task": {"queue": "email"},
    "hps_core.tasks.send_generic_email": {"queue": "email"},
    "hps_core.tasks.send_bulk_emails": {"queue": "email"},
    
    # Tareas de monitorización
    "hps_core.tasks.monitor_hps_emails_task": {"queue": "email"},
    "hps_core.tasks.hourly_hps_monitoring_task": {"queue": "email"},
    "hps_core.tasks.weekly_hps_stats_task": {"queue": "email"},
    
    # Tareas de análisis
    "hps_core.tasks.analyze_emails_task": {"queue": "analysis"},
    "hps_core.tasks.process_hps_responses_task": {"queue": "analysis"},
    "hps_core.tasks.generate_reports_task": {"queue": "analysis"},
    
    # Tareas de expiración
    "hps_core.tasks.check_hps_expiration_task": {"queue": "email"},
    "hps_expiration.check_expiration": {"queue": "email"},
    
    # Por defecto, todas las tareas HPS van a cola email
    "hps_core.tasks.*": {"queue": "email"},
}

CELERY_TASK_DEFAULT_QUEUE = "default"
CELERY_TASK_QUEUES = {
    "default": {
        "exchange": "default",
        "routing_key": "default",
    },
    "email": {
        "exchange": "email",
        "routing_key": "email",
    },
    "analysis": {
        "exchange": "analysis",
        "routing_key": "analysis",
    },
}

# Celery Beat Schedule (tareas periódicas)
from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    # Verificación de HPS próximas a caducar (L-V a las 9:00 AM)
    'check-hps-expiration': {
        'task': 'hps_core.tasks.check_hps_expiration_task',
        'schedule': crontab(hour=9, minute=0, day_of_week='1-5'),  # L-V a las 9:00
    },
    # Monitorización horaria de correos (8:00 AM - 6:00 PM)
    'hourly-hps-monitoring': {
        'task': 'hps_core.tasks.monitor_hps_emails_task',
        'schedule': crontab(hour='8-18', minute=0),  # Cada hora entre 8:00 AM y 6:00 PM
    },
    # Estadísticas semanales (Lunes a las 8:00 AM)
    # TODO: Descomentar cuando se implemente weekly_hps_stats_task
    # 'weekly-hps-stats': {
    #     'task': 'hps_core.tasks.weekly_hps_stats_task',
    #     'schedule': crontab(hour=8, minute=0, day_of_week=1),  # Lunes a las 8:00 AM
    # },
}